sudo: false
language: python
cache: pip
python:
- '2.7'
- '3.5'
env:
- PACKAGES="Django>=1.8,<1.9"
- PACKAGES="Django>=1.8,<1.9 django-threadedcomments>=1.1"
- PACKAGES="Django>=1.9,<1.10"
- PACKAGES="Django>=1.9,<1.10 django-threadedcomments>=1.1"
- PACKAGES="Django>=1.10,<1.11"
- PACKAGES="Django>=1.10,<1.11 django-threadedcomments>=1.1"
- PACKAGES='https://github.com/django/django/archive/master.tar.gz'
matrix:
  allow_failures:
  - env: PACKAGES='https://github.com/django/django/archive/master.tar.gz'
before_install:
- pip install codecov
install:
- pip install -U pip wheel
- pip install $PACKAGES mock -e .
script:
- coverage run example/manage.py test
after_success:
- codecov
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.freenode.org#django-fluent
    template:
    - '%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}'
    skip_join: true
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: UQYHU07XN2kSAea1wFMMm9OsDJdavodhQsE8oT3SjxdXCbfBe/M1HXE8lbY2sZetWNiyQrZfodICDxhquQsNnUQ9IwMiSkWyofdT7rFA/2txPtf8bCnVMb0j0qJL+eKhFLBdtAEhi3PmuD2DqxcQxyz81enwtCk3vq8hzBEZu4I=
    on_success: never
    on_failure: always
